version: "3"
services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - eehbv
    environment:
      MARIADB_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MARIADB_USER: "${MYSQL_USER}"
      MARIADB_PASSWORD: "${MYSQL_PASSWORD}"
      
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8080:80'
    networks:
      - eehbv
    links:
      - mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PMA_HOST: mariadb
      
volumes:
  mariadb:
  
networks:
  eehbv: